from ducktape.cluster.cluster_spec import ClusterSpec as ClusterSpec

class ServiceRegistry:
    def __init__(self) -> None: ...
    def __contains__(self, item) -> bool: ...
    def __iter__(self): ...
    def append(self, service) -> None: ...
    def to_json(self): ...
    def stop_all(self) -> None: ...
    def clean_all(self) -> None: ...
    def free_all(self) -> None: ...
    def min_cluster_spec(self): ...
    def errors(self): ...
