"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple

class Timestamp:
    """A nanosecond-resolution timestamp."""

    sec: int
    nsec: int

    def __init__(self, sec: int | float, nsec: int | float) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __gt__(self, other: Timestamp) -> bool: ...

class Sample(NamedTuple):
    name: str
    labels: dict[str, str]
    value: int | float
    timestamp: float | Timestamp | None
    exemplar: Exemplar | None

class Exemplar(NamedTuple):
    labels: dict[str, str]
    value: int | float
    timestamp: float | Timestamp | None
