from ducktape.command_line.defaults import ConsoleDefaults as ConsoleDefaults
from ducktape.utils.util import ducktape_version as ducktape_version

def create_ducktape_parser(): ...
def get_user_config_file(args): ...
def config_file_to_args_list(config_file): ...
def parse_args(args): ...
