from _typeshed import Incomplete

class ClientEventFactory:
    READY: str
    SETTING_UP: str
    RUNNING: str
    TEARING_DOWN: str
    FINISHED: str
    LOG: str
    TYPES: Incomplete
    test_id: Incomplete
    test_index: Incomplete
    source_id: Incomplete
    event_id: int
    def __init__(self, test_id, test_index, source_id) -> None: ...
    def copy(self, event): ...
    def running(self): ...
    def ready(self): ...
    def setting_up(self): ...
    def finished(self, result): ...
    def log(self, message, level): ...

class EventResponseFactory:
    def running(self, client_event): ...
    def ready(self, client_event, session_context, test_context, cluster): ...
    def setting_up(self, client_event): ...
    def finished(self, client_event): ...
    def log(self, client_event): ...
