from _typeshed import Incomplete

class LoggerMaker:
    logger_name: Incomplete
    def __init__(self, logger_name) -> None: ...
    @property
    def logger(self): ...
    @property
    def configured(self): ...
    def configure_logger(self) -> None: ...

def close_logger(logger) -> None: ...
