from _typeshed import Incomplete

class TestScheduler:
    cluster: Incomplete
    unschedulable: Incomplete
    def __init__(self, test_contexts, cluster) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def peek(self): ...
    def next(self): ...
