from _typeshed import Incomplete
from ducktape.cluster.cluster import Cluster as Cluster
from ducktape.cluster.cluster_spec import ClusterSpec as ClusterSpec
from ducktape.cluster.node_container import NodeContainer as NodeContainer

class FiniteSubcluster(Cluster):
    nodes: Incomplete
    def __init__(self, nodes) -> None: ...
    def do_alloc(self, cluster_spec): ...
    def free_single(self, node) -> None: ...
    def available(self): ...
    def used(self): ...
