load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "version",
    srcs = ["version.go"],
    importpath = "github.com/redpanda-data/redpanda/src/go/rpk/pkg/cli/version",
    visibility = ["//visibility:public"],
)
