load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

# support for running "tools" under bazel easily, see the script themselves for
# documentation

sh_binary(
    name = "run",
    srcs = ["run.sh"],
)
