#!/usr/bin/env bash
set -e

git -C /opt clone https://github.com/projectnessie/nessie
cd /opt/nessie
git reset --hard 25bd982ca37802123f328c066ddce517138779ef
ARCH=$(dpkg-architecture -q DEB_BUILD_ARCH)
JAVA_HOME="/usr/lib/jvm/java-21-openjdk-${ARCH}" ./gradlew --no-daemon --info :nessie-quarkus:quarkusBuild
mkdir -p deployments

mv servers/quarkus-server/build/quarkus-app/lib/ deployments/lib/
mv servers/quarkus-server/build/quarkus-app/*.jar deployments/
mv servers/quarkus-server/build/quarkus-app/app/ deployments/app/
mv servers/quarkus-server/build/quarkus-app/quarkus/ deployments/quarkus/
