#!/usr/bin/env bash
set -e
git -C /opt clone -b v1.45.1 --single-branch https://github.com/IBM/sarama.git
cd /opt/sarama/examples/interceptors
go mod tidy
go build
cd /opt/sarama/examples/http_server
go mod tidy
go build
cd /opt/sarama/examples/consumergroup
go mod tidy
go build
cd /opt/sarama/examples/sasl_scram_client
go mod tidy
go build
